import { ScheduleData, RuntimeConfig, Estate } from './schedule-types';

// Runtime configuration in minutes
export const DEFAULT_RUNTIMES: RuntimeConfig = {
  regular: {
    'ntp-vr': 15,    // NTP to VR: 15 minutes
    'vr-ntp': 15,    // VR to NTP: 15 minutes
    'sc-vr': 7,      // SC to VR: 7 minutes
    'sc-vc': 7,      // SC to VC: 7 minutes
    'vr-sc': 7,      // VR to SC: 7 minutes
    'vc-sc': 7,      // VC to SC: 7 minutes
  },
  special: {
    // Limited/Express service runtimes
    'ntp-sc': 15,    // NTP to SC direct: 15 minutes
    'sc-ntp': 15,    // SC to NTP direct: 15 minutes
    'sc-vr': 5,      // SC to VR: 5 minutes
    'sc-vc': 5,      // SC to VC: 5 minutes
    'vr-sc': 5,      // VR to SC: 5 minutes
    'vc-sc': 5,      // VC to SC: 5 minutes
  },
  // Note: Inter-estate direct routes are not official NR524 service
};

// Villa Rhapsody Schedule Data
// isStandard = true means Standard Service (stops at On Luk St/Sunshine City)
// isStandard = false means Limited Service (skips On Luk St via bypass)
export const SCHEDULE_VR: ScheduleData = {
  'ntp-vr': {
    weekday: [
      { time: '06:35', isStandard: false }, { time: '06:50', isStandard: false },
      { time: '07:00', isStandard: false }, { time: '07:15', isStandard: false },
      { time: '07:25', isStandard: false }, { time: '07:35', isStandard: false },
      { time: '07:50', isStandard: false }, { time: '08:00', isStandard: false },
      { time: '08:10', isStandard: false }, { time: '08:25', isStandard: false },
      { time: '08:35', isStandard: false }, { time: '08:45', isStandard: false },
      { time: '09:00', isStandard: false }, { time: '09:15', isStandard: false },
      { time: '09:35', isStandard: false }, { time: '09:55', isStandard: false },
      { time: '10:15', isStandard: false }, { time: '10:35', isStandard: false },
      { time: '10:55', isStandard: false }, { time: '11:15', isStandard: false },
      { time: '11:35', isStandard: false }, { time: '11:55', isStandard: false },
      { time: '12:15', isStandard: false }, { time: '12:35', isStandard: false },
      { time: '12:55', isStandard: false }, { time: '13:15', isStandard: false },
      { time: '13:45', isStandard: true },  { time: '14:20', isStandard: false },
      { time: '14:45', isStandard: true },  { time: '15:20', isStandard: false },
      { time: '15:35', isStandard: false }, { time: '15:55', isStandard: false },
      { time: '16:15', isStandard: false }, { time: '16:30', isStandard: false },
      { time: '16:45', isStandard: false }, { time: '17:00', isStandard: false },
      { time: '17:15', isStandard: false }, { time: '17:30', isStandard: false },
      { time: '17:45', isStandard: false }, { time: '18:00', isStandard: false },
      { time: '18:15', isStandard: false }, { time: '18:30', isStandard: false },
      { time: '18:45', isStandard: false }, { time: '19:00', isStandard: false },
      { time: '19:15', isStandard: false }, { time: '19:30', isStandard: false },
      { time: '19:45', isStandard: false },
      // Evening special services (limited/express via SC)
      { time: '20:00', isStandard: true },  { time: '20:15', isStandard: true },
      { time: '20:40', isStandard: true },  { time: '21:00', isStandard: true },
      { time: '21:20', isStandard: true },  { time: '21:40', isStandard: true },
      { time: '22:00', isStandard: true },  { time: '22:30', isStandard: true },
      { time: '23:00', isStandard: true },
    ],
    weekend: [
      { time: '06:35', isStandard: false }, { time: '06:55', isStandard: false },
      { time: '07:15', isStandard: false }, { time: '07:35', isStandard: false },
      { time: '07:55', isStandard: false }, { time: '08:15', isStandard: false },
      { time: '08:30', isStandard: false }, { time: '08:45', isStandard: false },
      { time: '09:00', isStandard: false }, { time: '09:15', isStandard: false },
      { time: '09:35', isStandard: false }, { time: '09:55', isStandard: false },
      { time: '10:15', isStandard: false }, { time: '10:35', isStandard: false },
      { time: '10:55', isStandard: false }, { time: '11:15', isStandard: false },
      { time: '11:35', isStandard: false }, { time: '11:55', isStandard: false },
      { time: '12:15', isStandard: false }, { time: '12:35', isStandard: false },
      { time: '12:55', isStandard: false }, { time: '13:15', isStandard: false },
      { time: '13:35', isStandard: false }, { time: '13:55', isStandard: false },
      { time: '14:15', isStandard: false }, { time: '14:35', isStandard: false },
      { time: '14:55', isStandard: false }, { time: '15:15', isStandard: false },
      { time: '15:35', isStandard: false }, { time: '15:55', isStandard: false },
      { time: '16:15', isStandard: false }, { time: '16:30', isStandard: false },
      { time: '16:45', isStandard: false }, { time: '17:00', isStandard: false },
      { time: '17:15', isStandard: false }, { time: '17:30', isStandard: false },
      { time: '17:45', isStandard: false }, { time: '18:00', isStandard: false },
      { time: '18:15', isStandard: false }, { time: '18:30', isStandard: false },
      { time: '18:45', isStandard: false }, { time: '19:00', isStandard: false },
      { time: '19:15', isStandard: false }, { time: '19:30', isStandard: false },
      { time: '19:45', isStandard: false }, { time: '20:00', isStandard: false },
      { time: '20:15', isStandard: false },
      { time: '20:35', isStandard: true },  { time: '21:00', isStandard: true },
      { time: '21:20', isStandard: true },  { time: '21:40', isStandard: true },
      { time: '22:00', isStandard: true },  { time: '22:30', isStandard: true },
      { time: '23:00', isStandard: true },
    ],
  },
  'vr-ntp': {
    weekday: [
      // Early morning limited services
      { time: '06:16', isStandard: true },  { time: '06:31', isStandard: true },
      { time: '06:41', isStandard: true },
      // Regular services
      { time: '07:01', isStandard: false }, { time: '07:11', isStandard: false },
      { time: '07:21', isStandard: false }, { time: '07:36', isStandard: false },
      { time: '07:46', isStandard: false }, { time: '07:56', isStandard: false },
      { time: '08:11', isStandard: false }, { time: '08:21', isStandard: false },
      { time: '08:31', isStandard: false }, { time: '08:46', isStandard: false },
      { time: '09:01', isStandard: false }, { time: '09:21', isStandard: false },
      { time: '09:41', isStandard: false }, { time: '10:01', isStandard: false },
      { time: '10:21', isStandard: false }, { time: '10:41', isStandard: false },
      { time: '11:01', isStandard: false }, { time: '11:21', isStandard: false },
      { time: '11:41', isStandard: false }, { time: '12:01', isStandard: false },
      { time: '12:21', isStandard: false }, { time: '12:41', isStandard: false },
      { time: '13:01', isStandard: false }, { time: '13:31', isStandard: false },
      { time: '14:01', isStandard: true },  { time: '14:30', isStandard: false },
      { time: '15:01', isStandard: true },  { time: '15:21', isStandard: false },
      { time: '15:41', isStandard: false }, { time: '16:01', isStandard: false },
      { time: '16:11', isStandard: false }, { time: '16:31', isStandard: false },
      { time: '16:46', isStandard: false }, { time: '17:01', isStandard: false },
      { time: '17:16', isStandard: false }, { time: '17:31', isStandard: false },
      { time: '17:46', isStandard: false }, { time: '18:01', isStandard: false },
      { time: '18:16', isStandard: false }, { time: '18:31', isStandard: false },
      { time: '18:46', isStandard: false }, { time: '19:01', isStandard: false },
      { time: '19:16', isStandard: false }, { time: '19:31', isStandard: false },
      { time: '19:46', isStandard: false }, { time: '20:01', isStandard: false },
      // Evening special services (via SC)
      { time: '20:21', isStandard: true },  { time: '20:41', isStandard: true },
      { time: '21:01', isStandard: true },  { time: '21:21', isStandard: true },
      { time: '21:41', isStandard: true },  { time: '22:11', isStandard: true },
      { time: '22:41', isStandard: true },
    ],
    weekend: [
      { time: '06:16', isStandard: true },  { time: '06:36', isStandard: true },
      { time: '07:01', isStandard: false }, { time: '07:21', isStandard: false },
      { time: '07:41', isStandard: false }, { time: '08:01', isStandard: false },
      { time: '08:16', isStandard: false }, { time: '08:31', isStandard: false },
      { time: '08:46', isStandard: false }, { time: '09:01', isStandard: false },
      { time: '09:21', isStandard: false }, { time: '09:41', isStandard: false },
      { time: '10:01', isStandard: false }, { time: '10:21', isStandard: false },
      { time: '10:41', isStandard: false }, { time: '11:01', isStandard: false },
      { time: '11:21', isStandard: false }, { time: '11:41', isStandard: false },
      { time: '12:01', isStandard: false }, { time: '12:21', isStandard: false },
      { time: '12:41', isStandard: false }, { time: '13:01', isStandard: false },
      { time: '13:21', isStandard: false }, { time: '13:41', isStandard: false },
      { time: '14:01', isStandard: false }, { time: '14:21', isStandard: false },
      { time: '14:41', isStandard: false }, { time: '15:01', isStandard: false },
      { time: '15:21', isStandard: false }, { time: '15:41', isStandard: false },
      { time: '16:01', isStandard: false }, { time: '16:15', isStandard: false },
      { time: '16:30', isStandard: false }, { time: '16:45', isStandard: false },
      { time: '17:00', isStandard: false }, { time: '17:15', isStandard: false },
      { time: '17:30', isStandard: false }, { time: '17:45', isStandard: false },
      { time: '18:00', isStandard: false }, { time: '18:15', isStandard: false },
      { time: '18:30', isStandard: false }, { time: '18:45', isStandard: false },
      { time: '19:00', isStandard: false }, { time: '19:15', isStandard: false },
      { time: '19:30', isStandard: false }, { time: '19:45', isStandard: false },
      { time: '20:01', isStandard: false }, { time: '20:21', isStandard: false },
      { time: '20:41', isStandard: true },  { time: '21:01', isStandard: true },
      { time: '21:21', isStandard: true },  { time: '21:41', isStandard: true },
      { time: '22:11', isStandard: true },  { time: '22:41', isStandard: true },
    ],
  },
  // Short route: Ma On Shan (Sunshine City) to/from Villa Rhapsody
  'mos-vr': {
    weekday: [
      { time: '07:10', isStandard: false }, { time: '07:22', isStandard: false },
      { time: '07:27', isStandard: false }, { time: '07:37', isStandard: false },
      { time: '07:47', isStandard: false }, { time: '07:57', isStandard: false },
      { time: '08:07', isStandard: false }, { time: '08:17', isStandard: false },
      { time: '08:27', isStandard: false }, { time: '08:37', isStandard: false },
      { time: '08:47', isStandard: false }, { time: '08:57', isStandard: false },
      { time: '09:10', isStandard: false }, { time: '09:30', isStandard: false },
      { time: '09:50', isStandard: false }, { time: '10:10', isStandard: false },
      { time: '10:30', isStandard: false }, { time: '10:50', isStandard: false },
      { time: '11:10', isStandard: false }, { time: '11:30', isStandard: false },
      { time: '11:50', isStandard: false }, { time: '12:10', isStandard: false },
      { time: '12:30', isStandard: false }, { time: '12:50', isStandard: false },
      { time: '13:10', isStandard: false }, { time: '13:30', isStandard: false },
      { time: '13:50', isStandard: false },
      { time: '14:00', isStandard: true },  { time: '14:30', isStandard: false },
      { time: '14:50', isStandard: false },
      { time: '15:00', isStandard: true },  { time: '15:30', isStandard: false },
      { time: '15:50', isStandard: false }, { time: '16:10', isStandard: false },
      { time: '16:30', isStandard: false }, { time: '16:50', isStandard: false },
      { time: '17:10', isStandard: false }, { time: '17:30', isStandard: false },
      { time: '17:50', isStandard: false }, { time: '18:10', isStandard: false },
      { time: '18:30', isStandard: false }, { time: '18:50', isStandard: false },
      { time: '19:10', isStandard: false }, { time: '19:30', isStandard: false },
      { time: '19:50', isStandard: false }, { time: '20:10', isStandard: false },
      { time: '20:15', isStandard: true },  { time: '20:30', isStandard: true },
      { time: '20:55', isStandard: true },  { time: '21:15', isStandard: true },
      { time: '21:35', isStandard: true },  { time: '21:55', isStandard: true },
      { time: '22:15', isStandard: true },  { time: '22:45', isStandard: true },
      { time: '23:15', isStandard: true },
    ],
    weekend: [
      { time: '07:10', isStandard: false }, { time: '07:30', isStandard: false },
      { time: '07:50', isStandard: false }, { time: '08:10', isStandard: false },
      { time: '08:30', isStandard: false }, { time: '08:50', isStandard: false },
      { time: '09:10', isStandard: false }, { time: '09:30', isStandard: false },
      { time: '09:50', isStandard: false }, { time: '10:10', isStandard: false },
      { time: '10:30', isStandard: false }, { time: '10:50', isStandard: false },
      { time: '11:10', isStandard: false }, { time: '11:30', isStandard: false },
      { time: '11:50', isStandard: false }, { time: '12:10', isStandard: false },
      { time: '12:30', isStandard: false }, { time: '12:50', isStandard: false },
      { time: '13:10', isStandard: false }, { time: '13:30', isStandard: false },
      { time: '13:50', isStandard: false }, { time: '14:10', isStandard: false },
      { time: '14:30', isStandard: false }, { time: '14:50', isStandard: false },
      { time: '15:10', isStandard: false }, { time: '15:30', isStandard: false },
      { time: '15:50', isStandard: false }, { time: '16:10', isStandard: false },
      { time: '16:30', isStandard: false }, { time: '16:50', isStandard: false },
      { time: '17:10', isStandard: false }, { time: '17:30', isStandard: false },
      { time: '17:50', isStandard: false }, { time: '18:10', isStandard: false },
      { time: '18:30', isStandard: false }, { time: '18:50', isStandard: false },
      { time: '19:10', isStandard: false }, { time: '19:30', isStandard: false },
      { time: '19:50', isStandard: false }, { time: '20:10', isStandard: false },
      { time: '20:30', isStandard: false },
      { time: '20:50', isStandard: true },  { time: '21:15', isStandard: true },
      { time: '21:35', isStandard: true },  { time: '21:55', isStandard: true },
      { time: '22:15', isStandard: true },  { time: '22:45', isStandard: true },
      { time: '23:15', isStandard: true },
    ],
  },
  'vr-mos': {
    weekday: [
      { time: '06:15', isStandard: true },  { time: '06:30', isStandard: true },
      { time: '06:40', isStandard: true },
      { time: '07:00', isStandard: false }, { time: '07:15', isStandard: false },
      { time: '07:20', isStandard: false }, { time: '07:30', isStandard: false },
      { time: '07:40', isStandard: false }, { time: '07:50', isStandard: false },
      { time: '08:00', isStandard: false }, { time: '08:10', isStandard: false },
      { time: '08:20', isStandard: false }, { time: '08:30', isStandard: false },
      { time: '08:40', isStandard: false }, { time: '08:50', isStandard: false },
      { time: '09:00', isStandard: false }, { time: '09:20', isStandard: false },
      { time: '09:40', isStandard: false }, { time: '10:00', isStandard: false },
      { time: '10:20', isStandard: false }, { time: '10:40', isStandard: false },
      { time: '11:00', isStandard: false }, { time: '11:20', isStandard: false },
      { time: '11:40', isStandard: false }, { time: '12:00', isStandard: false },
      { time: '12:20', isStandard: false }, { time: '12:40', isStandard: false },
      { time: '13:00', isStandard: false }, { time: '13:20', isStandard: false },
      { time: '13:40', isStandard: false },
      { time: '14:00', isStandard: true },  { time: '14:20', isStandard: false },
      { time: '14:40', isStandard: false },
      { time: '15:00', isStandard: true },  { time: '15:20', isStandard: false },
      { time: '15:40', isStandard: false }, { time: '16:00', isStandard: false },
      { time: '16:20', isStandard: false }, { time: '16:40', isStandard: false },
      { time: '17:00', isStandard: false }, { time: '17:20', isStandard: false },
      { time: '17:40', isStandard: false }, { time: '18:00', isStandard: false },
      { time: '18:20', isStandard: false }, { time: '18:40', isStandard: false },
      { time: '19:00', isStandard: false }, { time: '19:20', isStandard: false },
      { time: '19:40', isStandard: false }, { time: '20:00', isStandard: false },
      { time: '20:20', isStandard: true },  { time: '20:40', isStandard: true },
      { time: '21:00', isStandard: true },  { time: '21:20', isStandard: true },
      { time: '21:40', isStandard: true },  { time: '22:10', isStandard: true },
      { time: '22:40', isStandard: true },
    ],
    weekend: [
      { time: '06:15', isStandard: true },  { time: '06:35', isStandard: true },
      { time: '07:00', isStandard: false }, { time: '07:20', isStandard: false },
      { time: '07:40', isStandard: false }, { time: '08:00', isStandard: false },
      { time: '08:20', isStandard: false }, { time: '08:40', isStandard: false },
      { time: '09:00', isStandard: false }, { time: '09:20', isStandard: false },
      { time: '09:40', isStandard: false }, { time: '10:00', isStandard: false },
      { time: '10:20', isStandard: false }, { time: '10:40', isStandard: false },
      { time: '11:00', isStandard: false }, { time: '11:20', isStandard: false },
      { time: '11:40', isStandard: false }, { time: '12:00', isStandard: false },
      { time: '12:20', isStandard: false }, { time: '12:40', isStandard: false },
      { time: '13:00', isStandard: false }, { time: '13:20', isStandard: false },
      { time: '13:40', isStandard: false }, { time: '14:00', isStandard: false },
      { time: '14:20', isStandard: false }, { time: '14:40', isStandard: false },
      { time: '15:00', isStandard: false }, { time: '15:20', isStandard: false },
      { time: '15:40', isStandard: false }, { time: '16:00', isStandard: false },
      { time: '16:20', isStandard: false }, { time: '16:40', isStandard: false },
      { time: '17:00', isStandard: false }, { time: '17:20', isStandard: false },
      { time: '17:40', isStandard: false }, { time: '18:00', isStandard: false },
      { time: '18:20', isStandard: false }, { time: '18:40', isStandard: false },
      { time: '19:00', isStandard: false }, { time: '19:20', isStandard: false },
      { time: '19:40', isStandard: false }, { time: '20:00', isStandard: false },
      { time: '20:20', isStandard: false },
      { time: '20:40', isStandard: true },  { time: '21:00', isStandard: true },
      { time: '21:20', isStandard: true },  { time: '21:40', isStandard: true },
      { time: '22:10', isStandard: true },  { time: '22:40', isStandard: true },
    ],
  },

};

// Villa Concerto Schedule Data
export const SCHEDULE_VC: ScheduleData = {
  'ntp-vc': {
    weekday: [
      { time: '06:35', isStandard: false }, { time: '06:50', isStandard: false },
      { time: '07:00', isStandard: false }, { time: '07:15', isStandard: false },
      { time: '07:25', isStandard: false }, { time: '07:35', isStandard: false },
      { time: '07:50', isStandard: false }, { time: '08:00', isStandard: false },
      { time: '08:10', isStandard: false }, { time: '08:25', isStandard: false },
      { time: '08:35', isStandard: false }, { time: '08:45', isStandard: false },
      { time: '09:00', isStandard: false }, { time: '09:15', isStandard: false },
      { time: '09:35', isStandard: false }, { time: '09:55', isStandard: false },
      { time: '10:15', isStandard: false }, { time: '10:35', isStandard: false },
      { time: '10:55', isStandard: false }, { time: '11:15', isStandard: false },
      { time: '11:35', isStandard: false }, { time: '11:55', isStandard: false },
      { time: '12:15', isStandard: false }, { time: '12:35', isStandard: false },
      { time: '12:55', isStandard: false }, { time: '13:15', isStandard: false },
      { time: '13:45', isStandard: true },  { time: '14:20', isStandard: false },
      { time: '14:45', isStandard: true },  { time: '15:20', isStandard: false },
      { time: '15:35', isStandard: false }, { time: '15:55', isStandard: false },
      { time: '16:15', isStandard: false }, { time: '16:30', isStandard: false },
      { time: '16:45', isStandard: false }, { time: '17:00', isStandard: false },
      { time: '17:15', isStandard: false }, { time: '17:30', isStandard: false },
      { time: '17:45', isStandard: false }, { time: '18:00', isStandard: false },
      { time: '18:15', isStandard: false }, { time: '18:30', isStandard: false },
      { time: '18:45', isStandard: false }, { time: '19:00', isStandard: false },
      { time: '19:15', isStandard: false }, { time: '19:30', isStandard: false },
      { time: '19:45', isStandard: false },
      { time: '20:00', isStandard: true },  { time: '20:15', isStandard: true },
      { time: '20:40', isStandard: true },  { time: '21:00', isStandard: true },
      { time: '21:20', isStandard: true },  { time: '21:40', isStandard: true },
      { time: '22:00', isStandard: true },  { time: '22:30', isStandard: true },
      { time: '23:00', isStandard: true },
    ],
    weekend: [
      { time: '06:35', isStandard: false }, { time: '06:55', isStandard: false },
      { time: '07:15', isStandard: false }, { time: '07:35', isStandard: false },
      { time: '07:55', isStandard: false }, { time: '08:15', isStandard: false },
      { time: '08:30', isStandard: false }, { time: '08:45', isStandard: false },
      { time: '09:00', isStandard: false }, { time: '09:15', isStandard: false },
      { time: '09:35', isStandard: false }, { time: '09:55', isStandard: false },
      { time: '10:15', isStandard: false }, { time: '10:35', isStandard: false },
      { time: '10:55', isStandard: false }, { time: '11:15', isStandard: false },
      { time: '11:35', isStandard: false }, { time: '11:55', isStandard: false },
      { time: '12:15', isStandard: false }, { time: '12:35', isStandard: false },
      { time: '12:55', isStandard: false }, { time: '13:15', isStandard: false },
      { time: '13:35', isStandard: false }, { time: '13:55', isStandard: false },
      { time: '14:15', isStandard: false }, { time: '14:35', isStandard: false },
      { time: '14:55', isStandard: false }, { time: '15:15', isStandard: false },
      { time: '15:35', isStandard: false }, { time: '15:55', isStandard: false },
      { time: '16:15', isStandard: false }, { time: '16:30', isStandard: false },
      { time: '16:45', isStandard: false }, { time: '17:00', isStandard: false },
      { time: '17:15', isStandard: false }, { time: '17:30', isStandard: false },
      { time: '17:45', isStandard: false }, { time: '18:00', isStandard: false },
      { time: '18:15', isStandard: false }, { time: '18:30', isStandard: false },
      { time: '18:45', isStandard: false }, { time: '19:00', isStandard: false },
      { time: '19:15', isStandard: false }, { time: '19:30', isStandard: false },
      { time: '19:45', isStandard: false }, { time: '20:00', isStandard: false },
      { time: '20:15', isStandard: false },
      { time: '20:35', isStandard: true },  { time: '21:00', isStandard: true },
      { time: '21:20', isStandard: true },  { time: '21:40', isStandard: true },
      { time: '22:00', isStandard: true },  { time: '22:30', isStandard: true },
      { time: '23:00', isStandard: true },
    ],
  },
  'vc-ntp': {
    weekday: [
      { time: '06:15', isStandard: true },  { time: '06:30', isStandard: true },
      { time: '06:40', isStandard: true },
      { time: '07:00', isStandard: false }, { time: '07:10', isStandard: false },
      { time: '07:20', isStandard: false }, { time: '07:35', isStandard: false },
      { time: '07:45', isStandard: false }, { time: '07:55', isStandard: false },
      { time: '08:10', isStandard: false }, { time: '08:20', isStandard: false },
      { time: '08:30', isStandard: false }, { time: '08:45', isStandard: false },
      { time: '09:00', isStandard: false }, { time: '09:20', isStandard: false },
      { time: '09:40', isStandard: false }, { time: '10:00', isStandard: false },
      { time: '10:20', isStandard: false }, { time: '10:40', isStandard: false },
      { time: '11:00', isStandard: false }, { time: '11:20', isStandard: false },
      { time: '11:40', isStandard: false }, { time: '12:00', isStandard: false },
      { time: '12:20', isStandard: false }, { time: '12:40', isStandard: false },
      { time: '13:00', isStandard: false }, { time: '13:30', isStandard: false },
      { time: '14:00', isStandard: true },  { time: '14:30', isStandard: false },
      { time: '15:00', isStandard: true },  { time: '15:20', isStandard: false },
      { time: '15:40', isStandard: false }, { time: '16:00', isStandard: false },
      { time: '16:15', isStandard: false }, { time: '16:30', isStandard: false },
      { time: '16:45', isStandard: false }, { time: '17:00', isStandard: false },
      { time: '17:15', isStandard: false }, { time: '17:30', isStandard: false },
      { time: '17:45', isStandard: false }, { time: '18:00', isStandard: false },
      { time: '18:15', isStandard: false }, { time: '18:30', isStandard: false },
      { time: '18:45', isStandard: false }, { time: '19:00', isStandard: false },
      { time: '19:15', isStandard: false }, { time: '19:30', isStandard: false },
      { time: '19:45', isStandard: false }, { time: '20:00', isStandard: false },
      { time: '20:20', isStandard: true },  { time: '20:40', isStandard: true },
      { time: '21:00', isStandard: true },  { time: '21:20', isStandard: true },
      { time: '21:40', isStandard: true },  { time: '22:10', isStandard: true },
      { time: '22:40', isStandard: true },
    ],
    weekend: [
      { time: '06:15', isStandard: true },  { time: '06:35', isStandard: true },
      { time: '07:00', isStandard: false }, { time: '07:20', isStandard: false },
      { time: '07:40', isStandard: false }, { time: '08:00', isStandard: false },
      { time: '08:15', isStandard: false }, { time: '08:30', isStandard: false },
      { time: '08:45', isStandard: false }, { time: '09:00', isStandard: false },
      { time: '09:20', isStandard: false }, { time: '09:40', isStandard: false },
      { time: '10:00', isStandard: false }, { time: '10:20', isStandard: false },
      { time: '10:40', isStandard: false }, { time: '11:00', isStandard: false },
      { time: '11:20', isStandard: false }, { time: '11:40', isStandard: false },
      { time: '12:00', isStandard: false }, { time: '12:20', isStandard: false },
      { time: '12:40', isStandard: false }, { time: '13:00', isStandard: false },
      { time: '13:20', isStandard: false }, { time: '13:40', isStandard: false },
      { time: '14:00', isStandard: false }, { time: '14:20', isStandard: false },
      { time: '14:40', isStandard: false }, { time: '15:00', isStandard: false },
      { time: '15:20', isStandard: false }, { time: '15:40', isStandard: false },
      { time: '16:00', isStandard: false }, { time: '16:15', isStandard: false },
      { time: '16:30', isStandard: false }, { time: '16:45', isStandard: false },
      { time: '17:00', isStandard: false }, { time: '17:15', isStandard: false },
      { time: '17:30', isStandard: false }, { time: '17:45', isStandard: false },
      { time: '18:00', isStandard: false }, { time: '18:15', isStandard: false },
      { time: '18:30', isStandard: false }, { time: '18:45', isStandard: false },
      { time: '19:00', isStandard: false }, { time: '19:15', isStandard: false },
      { time: '19:30', isStandard: false }, { time: '19:45', isStandard: false },
      { time: '20:00', isStandard: false }, { time: '20:20', isStandard: false },
      { time: '20:40', isStandard: true },  { time: '21:00', isStandard: true },
      { time: '21:20', isStandard: true },  { time: '21:40', isStandard: true },
      { time: '22:10', isStandard: true },  { time: '22:40', isStandard: true },
    ],
  },
  'mos-vc': {
    weekday: [
      { time: '07:10', isStandard: false }, { time: '07:22', isStandard: false },
      { time: '07:27', isStandard: false }, { time: '07:37', isStandard: false },
      { time: '07:47', isStandard: false }, { time: '07:57', isStandard: false },
      { time: '08:07', isStandard: false }, { time: '08:17', isStandard: false },
      { time: '08:27', isStandard: false }, { time: '08:37', isStandard: false },
      { time: '08:47', isStandard: false }, { time: '08:57', isStandard: false },
      { time: '09:10', isStandard: false }, { time: '09:30', isStandard: false },
      { time: '09:50', isStandard: false }, { time: '10:10', isStandard: false },
      { time: '10:30', isStandard: false }, { time: '10:50', isStandard: false },
      { time: '11:10', isStandard: false }, { time: '11:30', isStandard: false },
      { time: '11:50', isStandard: false }, { time: '12:10', isStandard: false },
      { time: '12:30', isStandard: false }, { time: '12:50', isStandard: false },
      { time: '13:10', isStandard: false }, { time: '13:30', isStandard: false },
      { time: '13:50', isStandard: false },
      { time: '14:00', isStandard: true },  { time: '14:30', isStandard: false },
      { time: '14:50', isStandard: false },
      { time: '15:00', isStandard: true },  { time: '15:30', isStandard: false },
      { time: '15:50', isStandard: false }, { time: '16:10', isStandard: false },
      { time: '16:30', isStandard: false }, { time: '16:50', isStandard: false },
      { time: '17:10', isStandard: false }, { time: '17:30', isStandard: false },
      { time: '17:50', isStandard: false }, { time: '18:10', isStandard: false },
      { time: '18:30', isStandard: false }, { time: '18:50', isStandard: false },
      { time: '19:10', isStandard: false }, { time: '19:30', isStandard: false },
      { time: '19:50', isStandard: false }, { time: '20:10', isStandard: false },
      { time: '20:15', isStandard: true },  { time: '20:30', isStandard: true },
      { time: '20:55', isStandard: true },  { time: '21:15', isStandard: true },
      { time: '21:35', isStandard: true },  { time: '21:55', isStandard: true },
      { time: '22:15', isStandard: true },  { time: '22:45', isStandard: true },
      { time: '23:15', isStandard: true },
    ],
    weekend: [
      { time: '07:10', isStandard: false }, { time: '07:30', isStandard: false },
      { time: '07:50', isStandard: false }, { time: '08:10', isStandard: false },
      { time: '08:30', isStandard: false }, { time: '08:50', isStandard: false },
      { time: '09:10', isStandard: false }, { time: '09:30', isStandard: false },
      { time: '09:50', isStandard: false }, { time: '10:10', isStandard: false },
      { time: '10:30', isStandard: false }, { time: '10:50', isStandard: false },
      { time: '11:10', isStandard: false }, { time: '11:30', isStandard: false },
      { time: '11:50', isStandard: false }, { time: '12:10', isStandard: false },
      { time: '12:30', isStandard: false }, { time: '12:50', isStandard: false },
      { time: '13:10', isStandard: false }, { time: '13:30', isStandard: false },
      { time: '13:50', isStandard: false }, { time: '14:10', isStandard: false },
      { time: '14:30', isStandard: false }, { time: '14:50', isStandard: false },
      { time: '15:10', isStandard: false }, { time: '15:30', isStandard: false },
      { time: '15:50', isStandard: false }, { time: '16:10', isStandard: false },
      { time: '16:30', isStandard: false }, { time: '16:50', isStandard: false },
      { time: '17:10', isStandard: false }, { time: '17:30', isStandard: false },
      { time: '17:50', isStandard: false }, { time: '18:10', isStandard: false },
      { time: '18:30', isStandard: false }, { time: '18:50', isStandard: false },
      { time: '19:10', isStandard: false }, { time: '19:30', isStandard: false },
      { time: '19:50', isStandard: false }, { time: '20:10', isStandard: false },
      { time: '20:30', isStandard: false },
      { time: '20:50', isStandard: true },  { time: '21:15', isStandard: true },
      { time: '21:35', isStandard: true },  { time: '21:55', isStandard: true },
      { time: '22:15', isStandard: true },  { time: '22:45', isStandard: true },
      { time: '23:15', isStandard: true },
    ],
  },
  'vc-mos': {
    weekday: [
      { time: '06:15', isStandard: true },  { time: '06:30', isStandard: true },
      { time: '06:40', isStandard: true },
      { time: '07:00', isStandard: false }, { time: '07:15', isStandard: false },
      { time: '07:20', isStandard: false }, { time: '07:30', isStandard: false },
      { time: '07:40', isStandard: false }, { time: '07:50', isStandard: false },
      { time: '08:00', isStandard: false }, { time: '08:10', isStandard: false },
      { time: '08:20', isStandard: false }, { time: '08:30', isStandard: false },
      { time: '08:40', isStandard: false }, { time: '08:50', isStandard: false },
      { time: '09:00', isStandard: false }, { time: '09:20', isStandard: false },
      { time: '09:40', isStandard: false }, { time: '10:00', isStandard: false },
      { time: '10:20', isStandard: false }, { time: '10:40', isStandard: false },
      { time: '11:00', isStandard: false }, { time: '11:20', isStandard: false },
      { time: '11:40', isStandard: false }, { time: '12:00', isStandard: false },
      { time: '12:20', isStandard: false }, { time: '12:40', isStandard: false },
      { time: '13:00', isStandard: false }, { time: '13:20', isStandard: false },
      { time: '13:40', isStandard: false },
      { time: '14:00', isStandard: true },  { time: '14:20', isStandard: false },
      { time: '14:40', isStandard: false },
      { time: '15:00', isStandard: true },  { time: '15:20', isStandard: false },
      { time: '15:40', isStandard: false }, { time: '16:00', isStandard: false },
      { time: '16:20', isStandard: false }, { time: '16:40', isStandard: false },
      { time: '17:00', isStandard: false }, { time: '17:20', isStandard: false },
      { time: '17:40', isStandard: false }, { time: '18:00', isStandard: false },
      { time: '18:20', isStandard: false }, { time: '18:40', isStandard: false },
      { time: '19:00', isStandard: false }, { time: '19:20', isStandard: false },
      { time: '19:40', isStandard: false }, { time: '20:00', isStandard: false },
      { time: '20:20', isStandard: true },  { time: '20:40', isStandard: true },
      { time: '21:00', isStandard: true },  { time: '21:20', isStandard: true },
      { time: '21:40', isStandard: true },  { time: '22:10', isStandard: true },
      { time: '22:40', isStandard: true },
    ],
    weekend: [
      { time: '06:15', isStandard: true },  { time: '06:35', isStandard: true },
      { time: '07:00', isStandard: false }, { time: '07:20', isStandard: false },
      { time: '07:40', isStandard: false }, { time: '08:00', isStandard: false },
      { time: '08:20', isStandard: false }, { time: '08:40', isStandard: false },
      { time: '09:00', isStandard: false }, { time: '09:20', isStandard: false },
      { time: '09:40', isStandard: false }, { time: '10:00', isStandard: false },
      { time: '10:20', isStandard: false }, { time: '10:40', isStandard: false },
      { time: '11:00', isStandard: false }, { time: '11:20', isStandard: false },
      { time: '11:40', isStandard: false }, { time: '12:00', isStandard: false },
      { time: '12:20', isStandard: false }, { time: '12:40', isStandard: false },
      { time: '13:00', isStandard: false }, { time: '13:20', isStandard: false },
      { time: '13:40', isStandard: false }, { time: '14:00', isStandard: false },
      { time: '14:20', isStandard: false }, { time: '14:40', isStandard: false },
      { time: '15:00', isStandard: false }, { time: '15:20', isStandard: false },
      { time: '15:40', isStandard: false }, { time: '16:00', isStandard: false },
      { time: '16:20', isStandard: false }, { time: '16:40', isStandard: false },
      { time: '17:00', isStandard: false }, { time: '17:20', isStandard: false },
      { time: '17:40', isStandard: false }, { time: '18:00', isStandard: false },
      { time: '18:20', isStandard: false }, { time: '18:40', isStandard: false },
      { time: '19:00', isStandard: false }, { time: '19:20', isStandard: false },
      { time: '19:40', isStandard: false }, { time: '20:00', isStandard: false },
      { time: '20:20', isStandard: false },
      { time: '20:40', isStandard: true },  { time: '21:00', isStandard: true },
      { time: '21:20', isStandard: true },  { time: '21:40', isStandard: true },
      { time: '22:10', isStandard: true },  { time: '22:40', isStandard: true },
    ],
  },

};

// Get schedule by estate
export function getSchedule(estate: Estate): ScheduleData {
  return estate === 'vr' ? SCHEDULE_VR : SCHEDULE_VC;
}

// Route display names
export const ROUTE_NAMES: Record<string, { en: string; zh: string }> = {
  'ntp-vr': { en: 'New Town Plaza → Villa Rhapsody', zh: '新城市廣場 → 凱琴居' },
  'vr-ntp': { en: 'Villa Rhapsody → New Town Plaza', zh: '凱琴居 → 新城市廣場' },
  'ntp-vc': { en: 'New Town Plaza → Villa Concerto', zh: '新城市廣場 → 凱弦居' },
  'vc-ntp': { en: 'Villa Concerto → New Town Plaza', zh: '凱弦居 → 新城市廣場' },
  'mos-vr': { en: 'Sunshine City → Villa Rhapsody', zh: '新港城 → 凱琴居' },
  'vr-mos': { en: 'Villa Rhapsody → Sunshine City', zh: '凱琴居 → 新港城' },
  'mos-vc': { en: 'Sunshine City → Villa Concerto', zh: '新港城 → 凱弦居' },
  'vc-mos': { en: 'Villa Concerto → Sunshine City', zh: '凱弦居 → 新港城' },

};
